#! /usr/bin/env python3

from argparse import ArgumentParser
from pathlib import Path

def main(): 
    parser = ArgumentParser()

    args = parser.parse_args()


if __name__ == '__main__':
    main()